apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-webapp
  template:
    metadata:
      labels:
        app: todo-webapp
    spec:
      containers:
      - name: todo-container
        image: stjarnstoft/todoapp:7f977e157c4f88ef2b40d17776e39d2ab961a8ed
        ports:
        - containerPort: 80
        envFrom: 
        - configMapRef:
            name: app-config