apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-webapp
  template:
    metadata:
      labels:
        app: todo-webapp
    spec:
      containers:
      - name: todo-container
        image: stjarnstoft/todoapp:a9d82727bd8b244397c4c6ac1f07bbe572903f73
        ports:
        - containerPort: 80
        envFrom: 
        - configMapRef:
            name: app-config